### ISSUE TITLE
Error messages with invalid tokens

### ISSUE THREAD

**Issue by HaleTom** [zhyu/nadia#146]
When the token is `nil`, I see:

```
** (Mix) Could not start application app: App.Application.start(:normal, []) returned an error: shutdown: failed to start child: App.Telegram
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.bit_size(nil)
            (nadia 0.7.0) lib/nadia/api.ex:9: Nadia.API.build_url/1
            (nadia 0.7.0) lib/nadia/api.ex:118: Nadia.API.request/3
            (app 0.1.1) lib/app/telegram/telegram.ex:46: App.Telegram.init/1
            (stdlib 3.14.1) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14.1) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

When it is an invalid, non-nil, I see:

```
[error] Telegram bot failed to self-identify{:error, %Nadia.Model.Error{reason: "Not Found"}}
** (Mix) Could not start application app: App.Application.start(:normal, []) returned an error: shutdown: failed to start child: App.Telegram
```

Could these errors be improved?

**Comment by zhyu** [comment]
Maintainer triage (2026-06-26): Still partly valid on current master. Missing token config can resolve to nil and then fail while building the request URL. Invalid non-nil tokens are API responses from Telegram, but the missing-token case should be validated before HTTP with a token-safe error message. Keeping open as token/config validation work; tests should cover the default config path and explicit `%Nadia.Client{}` path.

**Comment by zhyu** [comment]
Fixed the missing-token case in Nadia 1.6.1. Requests with nil or missing token configuration now return `{:error, %Nadia.Model.Error{reason: :missing_token}}` before URL construction or HTTP. Invalid non-nil tokens still remain Telegram API responses, as expected. Tests cover both the default config path and an explicit `%Nadia.Client{}`. Relevant commit: 452b054 (`Normalize request setup errors`).
