### ISSUE TITLE
Error messages for incorrect arguments

### ISSUE THREAD

**Issue by HaleTom** [zhyu/nadia#147]
I was doing:

```
    response = Nadia.get_updates(unseen_id)
```

And got:

```
[error] GenServer #PID<0.605.0> terminating
** (FunctionClauseError) no function clause matching in Nadia.API.build_request/2
    (nadia 0.7.0) lib/nadia/api.ex:47: Nadia.API.build_request(43, nil)
    (nadia 0.7.0) lib/nadia/api.ex:119: Nadia.API.request/3
    (app 0.1.1) lib/app/telegram/telegram.ex:87: App.Telegram.handle_info/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :check
```

I needed to do instead:

```
    response = Nadia.get_updates(offset: unseen_id)
```

**Comment by etroynov** [comment]
@HaleTom Hi can you create this PR here:
https://github.com/etroynov/telegraph

**Comment by zhyu** [comment]
Maintainer triage (2026-06-26): This still reproduces on current master in the shared request path. Public wrappers document keyword-list options, but scalar input such as `Nadia.get_updates(43)` still reaches `Nadia.API.request/4` and fails with a function-clause error instead of a clear argument error or `{:error, %Nadia.Model.Error{}}`. Keeping open as argument-validation/error-message work; the fix should cover the shared option validation path and include tests for at least `get_updates/1`.

**Comment by zhyu** [comment]
Fixed in Nadia 1.6.1. Invalid option shapes such as `Nadia.get_updates(43)` now return an intentional `{:error, %Nadia.Model.Error{reason: :invalid_options}}` before any HTTP request instead of raising a low-level function-clause error. The regression is covered by tests for both the public `get_updates/1` wrapper and the shared request path. Relevant commit: 452b054 (`Normalize request setup errors`).
